baseURL = ""
languageCode = "ko-kr"
title = "myund's blog"
theme = "triplemode"

[params]
favicon = "img/favicon.ico"
description = "myund's blog"
disqus_shortname = ""
google_analytics = "G-L3NCZF8X4R"

str_next_post = "Next post"
str_previous_post = "Previous post"
str_next_page = "Next"
str_previous_page = "Prev"

[taxonomies]
    category = "categories"
    tag = "tags"
    subcategory = "subcategories"

[permalinks]
  development = "/:sections/:year/:month/:day/:filename.html"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

	[params.footer]
		enable=true
		copyright = "mingzzi"

    [[params.footer.social]]
		icon = "fa-github"
		url= "https://github.com/skye3133"
		label = "GitHub"

	[[params.footer.social]]
		icon = "fa-linkedin"
		url= "https://www.linkedin.com/in/hyunji-kim-b90b39208/"
		label = "Linkedin"